# Generated by Django 3.1.7 on 2021-04-23 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210423_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='Street',
            new_name='street',
        ),
    ]
